-- Recruiting ATS: initial PostgreSQL schema.

CREATE TABLE users (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  google_subject  text UNIQUE,
  email           text NOT NULL,
  full_name       text NOT NULL DEFAULT '',
  avatar_url      text NOT NULL DEFAULT '',
  is_active       boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  last_login_at   timestamptz
);

CREATE UNIQUE INDEX users_email_uq ON users (lower(email));


CREATE TABLE vacancies (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number      bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  name        text NOT NULL,
  status      text NOT NULL CHECK (status IN ('Открыта', 'На паузе', 'Закрыта')),
  comment     text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);


CREATE TABLE sources (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number      bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  name        text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);

CREATE UNIQUE INDEX sources_name_active_uq
  ON sources (lower(name)) WHERE deleted_at IS NULL;


CREATE TABLE responsibles (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number       bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  last_name    text NOT NULL,
  first_name   text NOT NULL,
  middle_name  text NOT NULL DEFAULT '',
  email        text NOT NULL DEFAULT '',
  user_id      uuid REFERENCES users (id),
  stages       text[] NOT NULL DEFAULT '{}',
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  deleted_at   timestamptz
);

-- Один пользователь может быть привязан не более чем к одному ответственному.
CREATE UNIQUE INDEX responsibles_user_active_uq
  ON responsibles (user_id) WHERE deleted_at IS NULL AND user_id IS NOT NULL;


CREATE TABLE interview_templates (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number      bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  name        text NOT NULL,
  vacancy_id  uuid NOT NULL REFERENCES vacancies (id),
  stage       text NOT NULL,
  required    boolean NOT NULL DEFAULT false,
  questions   jsonb NOT NULL DEFAULT '[]',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz
);

-- Для пары вакансия + этап допускается не более одного обязательного шаблона.
CREATE UNIQUE INDEX interview_templates_required_uq
  ON interview_templates (vacancy_id, stage)
  WHERE required AND deleted_at IS NULL;


-- Метаданные файлов. Содержимое лежит в Google Drive (drive_file_id)
-- либо, для импортированных записей без Drive ID, по внешней ссылке (external_url).
CREATE TABLE files (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  drive_file_id  text UNIQUE,
  external_url   text,
  original_name  text NOT NULL,
  mime_type      text NOT NULL DEFAULT 'application/octet-stream',
  size_bytes     bigint,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CHECK (drive_file_id IS NOT NULL OR external_url IS NOT NULL)
);


CREATE TABLE candidates (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number               bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  last_name            text NOT NULL,
  first_name           text NOT NULL,
  middle_name          text NOT NULL DEFAULT '',
  vacancy_id           uuid NOT NULL REFERENCES vacancies (id),
  status               text NOT NULL DEFAULT 'Новый',
  phone                text NOT NULL,
  email                text NOT NULL DEFAULT '',
  telegram             text NOT NULL DEFAULT '',
  telegram_url         text NOT NULL DEFAULT '',
  linkedin             text NOT NULL DEFAULT '',
  github               text NOT NULL DEFAULT '',
  source_id            uuid REFERENCES sources (id),
  salary_expectation   bigint CHECK (salary_expectation BETWEEN 0 AND 10000000),
  recruiter_id         uuid NOT NULL REFERENCES responsibles (id),
  hr_responsible_id    uuid NOT NULL REFERENCES responsibles (id),
  tech_interviewer_id  uuid NOT NULL REFERENCES responsibles (id),
  -- Папка кандидата в Google Drive; создаётся при первой загрузке резюме.
  drive_folder_id      text,
  comment              text NOT NULL DEFAULT '',
  links                jsonb NOT NULL DEFAULT '[]',
  rejection_reason     text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  archived_at          timestamptz
);

CREATE INDEX candidates_active_idx ON candidates (created_at) WHERE archived_at IS NULL;
CREATE INDEX candidates_archived_idx ON candidates (archived_at) WHERE archived_at IS NOT NULL;


CREATE TABLE candidate_resumes (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id  uuid NOT NULL REFERENCES candidates (id),
  file_id       uuid NOT NULL REFERENCES files (id),
  uploaded_at   timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX candidate_resumes_candidate_idx ON candidate_resumes (candidate_id, uploaded_at DESC);


CREATE TABLE interviews (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id      uuid NOT NULL REFERENCES candidates (id),
  vacancy_id        uuid NOT NULL REFERENCES vacancies (id),
  stage             text NOT NULL,
  from_status       text NOT NULL,
  to_status         text NOT NULL,
  template_id       uuid REFERENCES interview_templates (id),
  template_name     text NOT NULL DEFAULT '',
  responsible_id    uuid REFERENCES responsibles (id),
  interviewer_last_name    text NOT NULL DEFAULT '',
  interviewer_first_name   text NOT NULL DEFAULT '',
  interviewer_middle_name  text NOT NULL DEFAULT '',
  answers           jsonb NOT NULL DEFAULT '[]',
  comment           text NOT NULL DEFAULT '',
  result            text NOT NULL DEFAULT '',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  deleted_at        timestamptz
);

CREATE INDEX interviews_candidate_idx ON interviews (candidate_id) WHERE deleted_at IS NULL;


-- Append-only журнал переходов статусов.
CREATE TABLE candidate_status_log (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  candidate_id         uuid NOT NULL REFERENCES candidates (id),
  candidate_number     bigint,
  candidate_full_name  text NOT NULL DEFAULT '',
  from_status          text NOT NULL DEFAULT '',
  to_status            text NOT NULL,
  responsible_id       uuid REFERENCES responsibles (id),
  responsible_name     text NOT NULL DEFAULT '',
  changed_by_user_id   uuid REFERENCES users (id),
  changed_by_name      text NOT NULL DEFAULT '',
  changed_by_email     text NOT NULL DEFAULT '',
  comment              text NOT NULL DEFAULT '',
  created_at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX candidate_status_log_candidate_idx ON candidate_status_log (candidate_id, created_at);

CREATE FUNCTION candidate_status_log_append_only() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'candidate_status_log is append-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER candidate_status_log_no_update_delete
  BEFORE UPDATE OR DELETE ON candidate_status_log
  FOR EACH ROW EXECUTE FUNCTION candidate_status_log_append_only();


CREATE TABLE candidate_drafts (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  token           text NOT NULL UNIQUE,
  data            jsonb NOT NULL DEFAULT '{}',
  resume_file_id  uuid REFERENCES files (id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  expires_at      timestamptz NOT NULL,
  used_at         timestamptz,
  candidate_id    uuid REFERENCES candidates (id)
);


CREATE TABLE dictionaries (
  category  text NOT NULL,
  value     text NOT NULL,
  position  integer NOT NULL DEFAULT 0,
  PRIMARY KEY (category, value)
);

INSERT INTO dictionaries (category, value, position) VALUES
  ('Статусы кандидата', 'Новый', 1),
  ('Статусы кандидата', 'HR screening', 2),
  ('Статусы кандидата', 'Техническое интервью', 3),
  ('Статусы кандидата', 'Финальное интервью', 4),
  ('Статусы кандидата', 'Offer', 5),
  ('Статусы кандидата', 'Hired', 6),
  ('Статусы кандидата', 'Отказ', 7),
  ('Статусы вакансии', 'Открыта', 1),
  ('Статусы вакансии', 'На паузе', 2),
  ('Статусы вакансии', 'Закрыта', 3);


-- Хранилище сессий для connect-pg-simple.
CREATE TABLE session (
  sid     varchar NOT NULL PRIMARY KEY,
  sess    json NOT NULL,
  expire  timestamp(6) NOT NULL
);

CREATE INDEX session_expire_idx ON session (expire);
