-- Шаблоны вакансий: готовый набор этапов — шаблон вопросов и обязательность на каждом этапе.
-- Новую вакансию можно создать из шаблона: этапы копируются в неё один раз, дальше вакансия
-- и шаблон меняются независимо. Таблица vacancy_templates — это этапы конкретной вакансии
-- (привязки шаблонов вопросов), поэтому шаблон вакансии называется preset.

-- ===================== Шаблоны вакансий =====================

CREATE TABLE vacancy_presets (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  number          bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  name            text NOT NULL,
  -- Обязательные этапы (как vacancies.required_stages): при переходе нужен итог,
  -- а если на этапе есть шаблон вопросов — ещё и ответы.
  required_stages text[] NOT NULL DEFAULT '{}',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  archived_at     timestamptz,
  deleted_at      timestamptz,
  -- В корзину попадает только архивная запись.
  CONSTRAINT vacancy_presets_deleted_archived CHECK (deleted_at IS NULL OR archived_at IS NOT NULL)
);

-- Названия уникальны (без учёта регистра и пробелов по краям) среди неудалённых.
CREATE UNIQUE INDEX vacancy_presets_name_active_uq
  ON vacancy_presets (lower(btrim(name))) WHERE deleted_at IS NULL;

-- Шаблоны вопросов на этапах шаблона вакансии — как vacancy_templates у вакансии:
-- на этапе не больше одного шаблона, required совпадает с required_stages.
CREATE TABLE vacancy_preset_templates (
  preset_id   uuid NOT NULL REFERENCES vacancy_presets (id) ON DELETE CASCADE,
  stage       text NOT NULL,
  template_id uuid NOT NULL REFERENCES interview_templates (id) ON DELETE CASCADE,
  required    boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (preset_id, stage)
);

CREATE INDEX vacancy_preset_templates_template_idx ON vacancy_preset_templates (template_id);

-- Из какого шаблона создана вакансия — только для справки («создано вакансий» у шаблона).
-- Окончательное удаление шаблона вакансию не трогает.
ALTER TABLE vacancies ADD COLUMN preset_id uuid REFERENCES vacancy_presets (id) ON DELETE SET NULL;
CREATE INDEX vacancies_preset_idx ON vacancies (preset_id) WHERE preset_id IS NOT NULL;

-- ===================== Журнал изменений =====================

ALTER TABLE audit_log DROP CONSTRAINT audit_log_entity_type_check;
ALTER TABLE audit_log ADD CONSTRAINT audit_log_entity_type_check
  CHECK (entity_type IN ('candidate', 'vacancy', 'source', 'template', 'interview', 'user', 'vacancy_preset'));
